version: "3.3" 
services: 
  web: 
    build: .
    ports: 
      - 5000:80
    depends_on: 
      - database
  database:
    image: postgres 
    restart: always 
    env_file: ./src/database.conf
    volumes:
    - db_volume:/var/lib/postgresql
volumes:
  db_volume: